### ISSUE TITLE
Menu Mobile button not clickable

### ISSUE THREAD

**Issue by tlartaud** [marvinlabs/wpca-twenty-twelve#2]
Mobile menu button not working on responsive view.

**Comment by tlartaud** [comment]
forum : http://wp-customerarea.com/support/topic/demo-theme/#post-27774
demo : http://demos.wp-customerarea.com/freelancers/

**Comment by felixghy** [comment]
waiting for the fix! thank you

**Comment by tlartaud** [comment]
@felixghy Hi, sorry for the delay, had no time for this and then i forgot.

Can you please try to apply this change to your site ?
It will be fixed in the next version but u can actually apply the patch by yourself before @vpratfr release the new build.

Regards.

**Comment by felixghy** [comment]
@tlartaud i never used github, could you pls advise how to apply the change to current site? manually copy paste or auto deployment?
thank you

**Comment by tlartaud** [comment]
@felixghy just follow the link, read modifications applied and apply them manually to tour thème.

**Comment by felixghy** [comment]
I applied the patch and it works now! thank you very much!
